import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { PostQuery } from "../src/queries";
import { useQuery } from "@apollo/client";

export default function Home() {
  const { data, error, loading } = useQuery(PostQuery);

  if (error) {
    console.log(error);
    return <h1> Error </h1>;
  }
  if (loading) {
    return <h1> Loading </h1>;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.posts.map((post) => (
          <div key={post.id}>
            <h1>{post.title}</h1>
            <p>{post.content.text}</p>
          </div>
        ))}
      </main>
    </div>
  );
}
